/**
 * The part catalogue. Every visible component on every machine (player or enemy)
 * is one of these definitions, and every stat here feeds the physical simulation.
 */
import type { MachineClass, PartDef, PartCategory, Rarity, SocketType } from '../types';
import { sock, surf, sym } from './sockets';

const ALL: MachineClass[] = ['ground', 'air', 'mech'];
const G: MachineClass[] = ['ground'];
const A: MachineClass[] = ['air'];
const M: MachineClass[] = ['mech'];

type Def = Omit<PartDef, 'size' | 'classes' | 'mount' | 'armor' | 'family' | 'stats'> &
  Partial<Pick<PartDef, 'size' | 'classes' | 'mount' | 'armor' | 'family' | 'stats'>>;

const MOUNT_BY_CAT: Partial<Record<PartCategory, SocketType[]>> = {
  frame: [],
  cockpit: ['cockpit'],
  suspension: ['axle'],
  wheel: ['hub'],
  track: ['track'],
  leg: ['hip'],
  actuator: ['joint'],
  foot: ['foot'],
  arm: ['shoulder'],
  melee: ['hand'],
  weapon: ['surface', 'hand', 'hardpoint'],
};

function P(d: Def): PartDef {
  return {
    size: [0.5, 0.5, 0.5],
    classes: ALL,
    mount: MOUNT_BY_CAT[d.category] ?? ['surface'],
    armor: 4,
    family: 'scrap',
    stats: {},
    ...d,
  } as PartDef;
}

// ---------------------------------------------------------------- FRAMES
const FRAMES: PartDef[] = [
  P({
    id: 'frm_buggy',
    name: 'Scrap Buggy Frame',
    category: 'frame',
    rootOf: 'ground',
    classes: G,
    rarity: 'common',
    mass: 260,
    hp: 420,
    armor: 10,
    value: 400,
    mesh: 'frame_buggy',
    desc: 'Welded tube chassis with room for four wheels, an engine and a dream.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.06, 0.05], [0, 1, 0], { label: 'Seat' }),
      ...sym(sock('axle_f', 'axle', [0.6, 0.0, -1.15], [1, 0, 0], { steer: true, label: 'Front Right Axle' })),
      ...sym(sock('axle_r', 'axle', [0.6, 0.0, 1.15], [1, 0, 0], { label: 'Rear Right Axle' })),
      surf('top_front', [0, 0.1, -1.08], [0, 1, 0], [1.0, 0.7], { label: 'Front Deck' }),
      surf('top_rear', [0, 0.1, 1.12], [0, 1, 0], [1.1, 0.8], { label: 'Rear Deck' }),
      surf('front', [0, 0.05, -1.72], [0, 0, -1], [1.3, 0.4], { label: 'Front' }),
      surf('rear', [0, 0.05, 1.72], [0, 0, 1], [1.3, 0.4], { label: 'Rear' }),
      ...sym(surf('side', [0.66, 0.1, 0.05], [1, 0, 0], [0.3, 1.1], { label: 'Right Side' })),
      surf('bottom', [0, -0.12, 0], [0, -1, 0], [0.8, 2.4], { label: 'Underside' }),
    ],
  }),
  P({
    id: 'frm_racer',
    name: 'Dart Scout Chassis',
    category: 'frame',
    rootOf: 'ground',
    classes: G,
    rarity: 'rare',
    family: 'suspension2',
    tech: 'suspension2',
    mass: 190,
    hp: 320,
    armor: 8,
    value: 3600,
    mesh: 'frame_racer',
    desc: 'Low, long and light. A sports-scout tub built for speed across the flats.',
    sockets: [
      sock('cockpit', 'cockpit', [0, -0.02, 0.15], [0, 1, 0], { label: 'Seat' }),
      ...sym(sock('axle_f', 'axle', [0.58, -0.05, -1.45], [1, 0, 0], { steer: true, label: 'Front Right Axle' })),
      ...sym(sock('axle_r', 'axle', [0.62, -0.05, 1.35], [1, 0, 0], { label: 'Rear Right Axle' })),
      surf('top_front', [0, 0.08, -1.35], [0, 1, 0], [0.9, 0.7], { label: 'Nose Deck' }),
      surf('top_rear', [0, 0.1, 1.3], [0, 1, 0], [1.1, 0.9], { label: 'Engine Deck' }),
      surf('front', [0, -0.02, -2.02], [0, 0, -1], [1.1, 0.3], { label: 'Front' }),
      surf('rear', [0, 0.02, 2.0], [0, 0, 1], [1.2, 0.35], { label: 'Rear' }),
      ...sym(surf('side', [0.64, 0.02, 0.1], [1, 0, 0], [0.25, 1.4], { label: 'Right Side' })),
      surf('bottom', [0, -0.14, 0], [0, -1, 0], [0.8, 3.0], { label: 'Underside' }),
    ],
  }),
  P({
    id: 'frm_pickup',
    name: 'Workhorse Pickup Frame',
    category: 'frame',
    rootOf: 'ground',
    classes: G,
    rarity: 'uncommon',
    mass: 520,
    hp: 680,
    armor: 12,
    value: 1500,
    mesh: 'frame_pickup',
    desc: 'Ladder-frame pickup with a long bed. Hauls salvage and anything you can bolt to it.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.28, -0.35], [0, 1, 0], { label: 'Cab' }),
      ...sym(sock('axle_f', 'axle', [0.72, 0.05, -1.55], [1, 0, 0], { steer: true, label: 'Front Right Axle' })),
      ...sym(sock('axle_r', 'axle', [0.72, 0.05, 1.45], [1, 0, 0], { label: 'Rear Right Axle' })),
      surf('top_front', [0, 0.36, -1.7], [0, 1, 0], [1.3, 1.0], { label: 'Hood' }),
      surf('top_rear', [0, 0.2, 1.35], [0, 1, 0], [1.5, 1.8], { label: 'Bed' }),
      surf('front', [0, 0.2, -2.42], [0, 0, -1], [1.6, 0.5], { label: 'Front' }),
      surf('rear', [0, 0.2, 2.42], [0, 0, 1], [1.6, 0.5], { label: 'Tailgate' }),
      ...sym(surf('side', [0.86, 0.3, 0.6], [1, 0, 0], [0.4, 2.6], { label: 'Right Side' })),
      surf('bottom', [0, -0.08, 0], [0, -1, 0], [1.0, 3.6], { label: 'Underside' }),
    ],
  }),
  P({
    id: 'frm_hauler',
    name: 'Mule Six-Wheel Frame',
    category: 'frame',
    rootOf: 'ground',
    classes: G,
    rarity: 'rare',
    family: 'heavyframes',
    tech: 'heavyframes',
    mass: 1150,
    hp: 1150,
    armor: 16,
    value: 4800,
    mesh: 'frame_hauler',
    desc: 'Three axles of military-surplus truck. Carries armor, cargo and big guns without complaint.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.38, -2.15], [0, 1, 0], { label: 'Cab' }),
      ...sym(sock('axle_f', 'axle', [0.86, 0.05, -2.2], [1, 0, 0], { steer: true, label: 'Front Right Axle' })),
      ...sym(sock('axle_m', 'axle', [0.86, 0.05, 0.85], [1, 0, 0], { label: 'Middle Right Axle' })),
      ...sym(sock('axle_r', 'axle', [0.86, 0.05, 2.3], [1, 0, 0], { label: 'Rear Right Axle' })),
      surf('deck', [0, 0.3, 1.25], [0, 1, 0], [1.9, 3.4], { label: 'Cargo Deck' }),
      surf('top_mid', [0, 0.3, -0.75], [0, 1, 0], [1.7, 0.9], { label: 'Mid Deck' }),
      surf('front', [0, 0.35, -3.22], [0, 0, -1], [1.9, 0.6], { label: 'Front' }),
      surf('rear', [0, 0.35, 3.22], [0, 0, 1], [1.9, 0.6], { label: 'Rear' }),
      ...sym(surf('side', [1.0, 0.35, 0.6], [1, 0, 0], [0.45, 4.8], { label: 'Right Side' })),
      surf('bottom', [0, -0.1, 0], [0, -1, 0], [1.2, 5.0], { label: 'Underside' }),
    ],
  }),
  P({
    id: 'frm_hull',
    name: 'Bastion Tracked Hull',
    category: 'frame',
    rootOf: 'ground',
    classes: G,
    rarity: 'epic',
    family: 'tracks',
    tech: 'tracks',
    mass: 1900,
    hp: 1700,
    armor: 26,
    value: 9500,
    mesh: 'frame_hull',
    faction: 'authority',
    desc: 'A welded armour hull for track units. Slow, stubborn and very hard to kill.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.5, -1.2], [0, 1, 0], { label: 'Hatch' }),
      ...sym(sock('track', 'track', [1.02, -0.05, 0], [1, 0, 0], { label: 'Right Track Mount' })),
      surf('deck', [0, 0.58, 0.45], [0, 1, 0], [1.7, 2.8], { label: 'Turret Deck' }),
      surf('glacis', [0, 0.25, -2.62], [0, 0.45, -1], [1.8, 0.7], { label: 'Glacis' }),
      surf('rear', [0, 0.3, 2.72], [0, 0, 1], [1.8, 0.6], { label: 'Rear' }),
      ...sym(surf('side', [0.98, 0.45, 0.1], [1, 0, 0], [0.2, 4.4], { label: 'Right Side' })),
      surf('bottom', [0, -0.3, 0], [0, -1, 0], [1.4, 4.4], { label: 'Belly' }),
    ],
  }),
  P({
    id: 'frm_quad',
    name: 'Skeeter Quad Frame',
    category: 'frame',
    rootOf: 'air',
    classes: A,
    rarity: 'common',
    mass: 140,
    hp: 300,
    armor: 6,
    value: 500,
    mesh: 'frame_quad',
    desc: 'Four carbon-and-conduit arms around a pod. Every rotor placement matters.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.2, -0.3], [0, 1, 0], { label: 'Pod' }),
      ...sym(surf('rotor_f', [1.32, 0.15, -1.18], [0, 1, 0], [0.35, 0.35], { label: 'Front Right Arm' })),
      ...sym(surf('rotor_r', [1.32, 0.15, 1.18], [0, 1, 0], [0.35, 0.35], { label: 'Rear Right Arm' })),
      surf('top', [0, 0.22, 0.45], [0, 1, 0], [0.7, 0.6], { label: 'Spine' }),
      surf('bottom', [0, -0.22, 0.05], [0, -1, 0], [0.8, 1.2], { label: 'Belly' }),
      surf('front', [0, -0.02, -0.74], [0, 0, -1], [0.8, 0.3], { label: 'Nose' }),
      surf('rear', [0, 0.0, 0.74], [0, 0, 1], [0.8, 0.3], { label: 'Tail' }),
      ...sym(surf('side', [0.5, 0.0, 0.25], [1, 0, 0], [0.25, 0.8], { label: 'Right Side' })),
    ],
  }),
  P({
    id: 'frm_heli',
    name: 'Hornet Heli Fuselage',
    category: 'frame',
    rootOf: 'air',
    classes: A,
    rarity: 'uncommon',
    family: 'rotors2',
    tech: 'rotors2',
    mass: 380,
    hp: 560,
    armor: 10,
    value: 1900,
    mesh: 'frame_heli',
    desc: 'Classic helicopter body with a long tail boom. Needs a tail rotor or it spins like a top.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.1, -1.35], [0, 1, 0], { label: 'Cockpit' }),
      surf('mast', [0, 0.95, 0.1], [0, 1, 0], [0.6, 0.6], { label: 'Rotor Mast' }),
      surf('top_rear', [0, 0.72, 1.15], [0, 1, 0], [0.7, 0.8], { label: 'Engine Deck' }),
      ...sym(surf('tail', [0.13, 0.55, 5.3], [1, 0, 0], [0.4, 0.45], { label: 'Right Tail' })),
      surf('tail_top', [0, 0.78, 5.2], [0, 1, 0], [0.2, 0.5], { label: 'Tail Top' }),
      ...sym(surf('side', [0.62, -0.05, 0.1], [1, 0, 0], [0.55, 1.5], { label: 'Right Stub' })),
      surf('bottom', [0, -0.62, -0.2], [0, -1, 0], [0.9, 2.6], { label: 'Belly' }),
      surf('nose', [0, -0.25, -2.3], [0, 0, -1], [0.5, 0.35], { label: 'Chin' }),
    ],
  }),
  P({
    id: 'frm_vtol',
    name: 'Kestrel VTOL Airframe',
    category: 'frame',
    rootOf: 'air',
    classes: A,
    rarity: 'rare',
    family: 'aero',
    tech: 'aero',
    mass: 720,
    hp: 820,
    armor: 14,
    value: 5600,
    mesh: 'frame_vtol',
    faction: 'authority',
    desc: 'Blended lifting body with four nacelle hardpoints and wing roots. A gunship in waiting.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.32, -1.65], [0, 1, 0], { label: 'Cockpit' }),
      ...sym(surf('nacelle_f', [1.05, 0.42, -1.25], [0, 1, 0], [0.6, 0.6], { label: 'Front Right Nacelle' })),
      ...sym(surf('nacelle_r', [1.05, 0.42, 1.55], [0, 1, 0], [0.6, 0.6], { label: 'Rear Right Nacelle' })),
      ...sym(surf('wing', [1.25, 0.05, 0.3], [1, 0, 0], [0.4, 1.8], { label: 'Right Wing Root' })),
      surf('top', [0, 0.5, 0.3], [0, 1, 0], [1.1, 1.6], { label: 'Spine' }),
      surf('bottom', [0, -0.42, 0.1], [0, -1, 0], [1.5, 3.4], { label: 'Belly' }),
      surf('rear', [0, 0.1, 2.58], [0, 0, 1], [1.6, 0.5], { label: 'Tail' }),
      surf('nose', [0, -0.05, -2.58], [0, 0, -1], [0.8, 0.4], { label: 'Nose' }),
    ],
  }),
  P({
    id: 'frm_scout_torso',
    name: 'Stilt Scout Torso',
    category: 'frame',
    rootOf: 'mech',
    classes: M,
    rarity: 'common',
    mass: 380,
    hp: 540,
    armor: 12,
    value: 600,
    mesh: 'torso_scout',
    desc: 'A compact two-leg walker torso. Hips below, shoulders either side, pilot up front.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.32, -0.25], [0, 1, 0], { label: 'Pilot Seat' }),
      ...sym(sock('hip', 'hip', [0.42, -0.58, 0.05], [0, -1, 0], { label: 'Right Hip' })),
      ...sym(sock('shoulder', 'shoulder', [0.72, 0.18, -0.05], [1, 0, 0], { label: 'Right Shoulder' })),
      surf('back', [0, 0.05, 0.58], [0, 0, 1], [0.9, 0.8], { label: 'Back' }),
      surf('top', [0, 0.6, 0.28], [0, 1, 0], [0.8, 0.5], { label: 'Top' }),
      surf('front', [0, -0.22, -0.58], [0, 0, -1], [0.9, 0.35], { label: 'Chest' }),
      ...sym(surf('side', [0.66, -0.25, 0.12], [1, 0, 0], [0.35, 0.7], { label: 'Right Flank' })),
    ],
  }),
  P({
    id: 'frm_walker_torso',
    name: 'Crab Walker Chassis',
    category: 'frame',
    rootOf: 'mech',
    classes: M,
    rarity: 'rare',
    family: 'heavyjoints',
    tech: 'heavyjoints',
    mass: 1250,
    hp: 1050,
    armor: 16,
    value: 5200,
    mesh: 'torso_walker',
    desc: 'Four-legged industrial walker body. Wide stance, heavy payload, unstoppable on rock.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.5, -1.05], [0, 1, 0], { label: 'Cab' }),
      ...sym(sock('hip_f', 'hip', [0.95, -0.45, -1.0], [0, -1, 0], { label: 'Front Right Hip' })),
      ...sym(sock('hip_r', 'hip', [0.95, -0.45, 1.0], [0, -1, 0], { label: 'Rear Right Hip' })),
      ...sym(sock('shoulder', 'shoulder', [1.15, 0.15, -1.2], [1, 0, 0], { label: 'Right Shoulder' })),
      surf('top', [0, 0.52, 0.45], [0, 1, 0], [1.8, 1.6], { label: 'Top Deck' }),
      surf('back', [0, 0.0, 1.42], [0, 0, 1], [1.8, 0.8], { label: 'Back' }),
      surf('front', [0, -0.12, -1.42], [0, 0, -1], [1.6, 0.5], { label: 'Front' }),
      ...sym(surf('side', [1.13, 0.05, 0.1], [1, 0, 0], [0.45, 0.9], { label: 'Right Side' })),
      surf('bottom', [0, -0.52, 0], [0, -1, 0], [1.2, 1.4], { label: 'Belly' }),
    ],
  }),
  P({
    id: 'frm_heavy_torso',
    name: 'Bulwark Assault Torso',
    category: 'frame',
    rootOf: 'mech',
    classes: M,
    rarity: 'epic',
    family: 'heavyframes',
    tech: 'heavyframes',
    mass: 1500,
    hp: 1450,
    armor: 22,
    value: 9000,
    mesh: 'torso_heavy',
    faction: 'authority',
    desc: 'Iron Authority assault torso. Broad shoulders built for enormous arms.',
    sockets: [
      sock('cockpit', 'cockpit', [0, 0.5, -0.45], [0, 1, 0], { label: 'Pilot Seat' }),
      ...sym(sock('hip', 'hip', [0.62, -0.88, 0.1], [0, -1, 0], { label: 'Right Hip' })),
      ...sym(sock('shoulder', 'shoulder', [1.12, 0.35, -0.05], [1, 0, 0], { label: 'Right Shoulder' })),
      surf('top', [0, 0.88, 0.3], [0, 1, 0], [1.4, 0.8], { label: 'Top' }),
      surf('back', [0, 0.1, 0.8], [0, 0, 1], [1.4, 1.1], { label: 'Back' }),
      surf('front', [0, -0.42, -0.8], [0, 0, -1], [1.4, 0.5], { label: 'Chest' }),
      ...sym(surf('side', [1.0, -0.3, 0.2], [1, 0, 0], [0.5, 0.9], { label: 'Right Flank' })),
    ],
  }),
];

// ---------------------------------------------------------------- COCKPITS
const COCKPITS: PartDef[] = [
  P({
    id: 'ckp_cage',
    name: 'Roll-Cage Seat',
    category: 'cockpit',
    classes: G,
    rarity: 'common',
    mass: 110,
    hp: 170,
    armor: 7,
    value: 150,
    mesh: 'cockpit_cage',
    desc: 'A bucket seat, a steering wheel and a cage of bent pipe between you and the world.',
    sockets: [surf('roof', [0, 1.28, 0.12], [0, 1, 0], [0.8, 0.7], { label: 'Cage Roof' }), surf('back', [0, 0.62, 0.62], [0, 0, 1], [0.8, 0.5], { label: 'Cage Back' })],
  }),
  P({
    id: 'ckp_cab',
    name: 'Steel Cab',
    category: 'cockpit',
    classes: G,
    rarity: 'uncommon',
    mass: 280,
    hp: 330,
    armor: 14,
    value: 900,
    mesh: 'cockpit_cab',
    desc: 'An enclosed truck cab with wire-mesh windows. Keeps the lead out and the dust in.',
    sockets: [surf('roof', [0, 1.36, 0.05], [0, 1, 0], [1.2, 1.0], { label: 'Cab Roof' })],
  }),
  P({
    id: 'ckp_armored',
    name: 'Armored Command Cab',
    category: 'cockpit',
    classes: G,
    rarity: 'rare',
    family: 'armor2',
    tech: 'armor2',
    mass: 520,
    hp: 540,
    armor: 24,
    value: 3200,
    mesh: 'cockpit_armored',
    faction: 'authority',
    desc: 'Slab-sided military cab with vision blocks instead of windows.',
    sockets: [surf('roof', [0, 1.22, 0.1], [0, 1, 0], [1.2, 1.0], { label: 'Cab Roof' })],
  }),
  P({
    id: 'ckp_canopy',
    name: 'Bubble Canopy',
    category: 'cockpit',
    classes: A,
    rarity: 'common',
    mass: 80,
    hp: 140,
    armor: 5,
    value: 200,
    mesh: 'cockpit_canopy',
    desc: 'Plexiglass bubble with an excellent view of everything shooting at you.',
  }),
  P({
    id: 'ckp_gunship',
    name: 'Tandem Gunship Cockpit',
    category: 'cockpit',
    classes: A,
    rarity: 'rare',
    family: 'armor2',
    tech: 'armor2',
    mass: 260,
    hp: 380,
    armor: 16,
    value: 3400,
    mesh: 'cockpit_gunship',
    faction: 'authority',
    desc: 'Stepped tandem cockpit with armoured glass. Built to hover in a firefight.',
  }),
  P({
    id: 'ckp_mech',
    name: 'Walker Pilot Pod',
    category: 'cockpit',
    classes: M,
    rarity: 'common',
    mass: 180,
    hp: 250,
    armor: 12,
    value: 300,
    mesh: 'cockpit_mech',
    desc: 'An armoured pod with a slit visor. It rocks with every step.',
  }),
  P({
    id: 'ckp_mech_heavy',
    name: 'Armored Command Pod',
    category: 'cockpit',
    classes: M,
    rarity: 'rare',
    family: 'armor2',
    tech: 'armor2',
    mass: 420,
    hp: 480,
    armor: 24,
    value: 3300,
    mesh: 'cockpit_mech_heavy',
    faction: 'authority',
    desc: 'Heavily armoured command pod with a sensor brow.',
  }),
  P({
    id: 'ckp_helix',
    name: 'Helix Neural Cockpit',
    category: 'cockpit',
    classes: ALL,
    rarity: 'epic',
    family: 'energy',
    mass: 120,
    hp: 320,
    armor: 18,
    value: 7500,
    mesh: 'cockpit_helix',
    faction: 'helix',
    blueprint: true,
    special: ['neural'],
    desc: 'A seamless white pod with direct neural fire control. Weapons track 30% faster.',
  }),
];

// ---------------------------------------------------------------- POWERTRAIN
const ENGINES: PartDef[] = [
  P({ id: 'eng_mower', name: 'Lawnmower Two-Stroke', category: 'engine', rarity: 'common', mass: 60, hp: 70, armor: 3, value: 120, mesh: 'engine', look: { layout: 'mower', cyl: 1 }, stats: { torque: 95, maxRpm: 7600, idleRpm: 1400, powerGen: 5, fuelUse: 0.25, heat: 5 }, desc: 'It buzzes, it smokes, it technically counts as an engine.' }),
  P({ id: 'eng_v4', name: 'Scrap V4', category: 'engine', rarity: 'common', mass: 170, hp: 150, armor: 5, value: 450, mesh: 'engine', look: { layout: 'v', cyl: 4 }, stats: { torque: 290, maxRpm: 6200, idleRpm: 900, powerGen: 12, fuelUse: 0.55, heat: 9 }, desc: 'Four cylinders salvaged from three different engines.' }),
  P({ id: 'eng_i6', name: 'Inline-6 Workhorse', category: 'engine', rarity: 'uncommon', family: 'combustion2', tech: 'combustion2', mass: 240, hp: 190, armor: 6, value: 1500, mesh: 'engine', look: { layout: 'inline', cyl: 6 }, stats: { torque: 440, maxRpm: 5900, idleRpm: 800, powerGen: 20, fuelUse: 0.75, heat: 12 }, desc: 'Smooth, reliable, tireless. The backbone of every settlement truck.' }),
  P({ id: 'eng_v8', name: 'Big-Block V8', category: 'engine', rarity: 'rare', family: 'combustion2', tech: 'combustion2', mass: 330, hp: 230, armor: 7, value: 4200, mesh: 'engine', look: { layout: 'v', cyl: 8, blower: true }, stats: { torque: 740, maxRpm: 5700, idleRpm: 850, powerGen: 30, fuelUse: 1.2, heat: 20 }, desc: 'Supercharged American iron. Rattles your fillings loose.' }),
  P({ id: 'eng_diesel', name: 'Deep-Rumble Diesel', category: 'engine', rarity: 'rare', family: 'combustion2', tech: 'combustion2', mass: 480, hp: 320, armor: 9, value: 4600, mesh: 'engine', look: { layout: 'inline', cyl: 6, diesel: true }, stats: { torque: 1350, maxRpm: 3400, idleRpm: 650, powerGen: 40, fuelUse: 1.1, heat: 16 }, special: ['diesel'], desc: 'Colossal torque at low revs. Moves mountains, slowly.' }),
  P({ id: 'eng_v12', name: 'Twin-Turbo V12', category: 'engine', rarity: 'epic', family: 'combustion2', mass: 420, hp: 270, armor: 8, value: 11000, mesh: 'engine', look: { layout: 'v', cyl: 12, turbo: true }, stats: { torque: 1080, maxRpm: 7200, idleRpm: 950, powerGen: 45, fuelUse: 1.9, heat: 28 }, desc: 'Pre-collapse supercar heart. Screams to seven thousand.' }),
  P({ id: 'eng_turbine', name: 'Gas Turbine Drive', category: 'engine', rarity: 'epic', family: 'turbines', tech: 'turbines', mass: 260, hp: 170, armor: 5, value: 9000, mesh: 'engine', look: { layout: 'turbine' }, stats: { torque: 820, maxRpm: 9000, idleRpm: 2500, powerGen: 70, fuelUse: 2.3, heat: 26 }, special: ['turbine'], desc: 'Light, powerful, thirsty. Whines like a jet at a standstill.' }),
  P({ id: 'eng_hellfire', name: 'Hellfire V16', category: 'engine', rarity: 'legendary', family: 'combustion2', mass: 560, hp: 330, armor: 9, value: 26000, mesh: 'engine', look: { layout: 'v', cyl: 16, blower: true, turbo: true }, blueprint: true, stats: { torque: 2300, maxRpm: 7400, idleRpm: 1000, powerGen: 60, fuelUse: 3.0, heat: 72 }, special: ['extreme heat'], desc: 'Monstrous torque and acceleration. Produces extreme heat — build your cooling around it or watch it cook itself.' }),
  P({ id: 'eng_flux', name: 'Möbius Flux Motor', category: 'engine', rarity: 'exotic', family: 'energy', mass: 150, hp: 200, armor: 8, value: 42000, mesh: 'engine', look: { layout: 'flux' }, faction: 'helix', unique: true, stats: { torque: 1500, maxRpm: 11000, idleRpm: 0, powerDraw: 420, heat: 10 }, special: ['electric drive', 'instant torque'], desc: 'Runs on electrical power instead of fuel. Full torque from zero RPM — if your grid can feed it.' }),
];

const GENERATORS: PartDef[] = [
  P({ id: 'gen_dynamo', name: 'Scrap Dynamo', category: 'generator', rarity: 'common', mass: 80, hp: 80, armor: 3, value: 250, mesh: 'generator', look: { style: 'dynamo' }, stats: { powerGen: 60, fuelUse: 0.35, heat: 6 }, desc: 'A lawn-engine bolted to a car alternator. Surprisingly dependable.' }),
  P({ id: 'gen_diesel', name: 'Diesel Generator', category: 'generator', rarity: 'uncommon', mass: 190, hp: 160, armor: 6, value: 1400, mesh: 'generator', look: { style: 'diesel' }, stats: { powerGen: 160, fuelUse: 0.8, heat: 12 }, desc: 'Industrial genset in a steel cage.' }),
  P({ id: 'gen_core_scrap', name: 'Scrap Power Core', category: 'generator', rarity: 'common', mass: 220, hp: 190, armor: 6, value: 520, mesh: 'generator', look: { style: 'core' }, stats: { powerGen: 150, fuelUse: 0.6, heat: 12 }, desc: 'A drum of batteries, a small turbine and a lot of tape. Walkers love it.' }),
  P({ id: 'gen_turbine', name: 'Turbine Generator', category: 'generator', rarity: 'rare', family: 'turbines', tech: 'turbines', mass: 170, hp: 130, armor: 5, value: 4800, mesh: 'generator', look: { style: 'turbine' }, stats: { powerGen: 340, fuelUse: 1.8, heat: 22 }, desc: 'High output, high consumption. Aircraft builders swear by it.' }),
  P({ id: 'gen_fuelcell', name: 'Fuel Cell Stack', category: 'generator', rarity: 'rare', family: 'batteries', tech: 'batteries', mass: 140, hp: 110, armor: 5, value: 5200, mesh: 'generator', look: { style: 'cell' }, stats: { powerGen: 230, fuelUse: 0.45, heat: 8 }, desc: 'Quiet, efficient and cool-running.' }),
  P({ id: 'gen_core_mil', name: 'Military Power Core', category: 'generator', rarity: 'epic', family: 'batteries', mass: 300, hp: 280, armor: 12, value: 12000, mesh: 'generator', look: { style: 'milcore' }, faction: 'authority', stats: { powerGen: 500, fuelUse: 1.0, heat: 20 }, desc: 'Iron Authority mech reactor. Armoured casing, enormous output.' }),
  P({ id: 'gen_fusion', name: 'Fusion Microcore', category: 'generator', rarity: 'legendary', family: 'energy', mass: 380, hp: 230, armor: 10, value: 30000, blueprint: true, mesh: 'generator', look: { style: 'fusion' }, stats: { powerGen: 950, heat: 30 }, special: ['no fuel', 'volatile'], desc: 'Nearly limitless power with no fuel at all. Detonates spectacularly when destroyed.' }),
  P({ id: 'gen_singularity', name: 'Helix Singularity Cell', category: 'generator', rarity: 'exotic', family: 'energy', mass: 90, hp: 150, armor: 8, value: 52000, unique: true, faction: 'helix', mesh: 'generator', look: { style: 'singularity' }, stats: { powerGen: 1600, heat: 45 }, special: ['anti-mass'], desc: 'Contains something that bends gravity. The whole machine weighs 25% less while it runs.' }),
];

const BATTERIES: PartDef[] = [
  P({ id: 'bat_lead', name: 'Lead-Acid Bank', category: 'battery', rarity: 'common', mass: 90, hp: 70, armor: 3, value: 150, mesh: 'battery', look: { style: 'lead' }, stats: { batteryCap: 500, maxDischarge: 140 }, desc: 'Six truck batteries zip-tied into a crate.' }),
  P({ id: 'bat_liion', name: 'Li-Ion Pack', category: 'battery', rarity: 'uncommon', family: 'batteries', tech: 'batteries', mass: 60, hp: 60, armor: 4, value: 1600, mesh: 'battery', look: { style: 'liion' }, stats: { batteryCap: 1600, maxDischarge: 320 }, desc: 'Dense, light and only occasionally on fire.' }),
  P({ id: 'bat_cap', name: 'Capacitor Bank', category: 'battery', rarity: 'rare', family: 'batteries', tech: 'batteries', mass: 110, hp: 80, armor: 5, value: 3600, mesh: 'battery', look: { style: 'cap' }, stats: { batteryCap: 900, maxDischarge: 3000 }, desc: 'Dumps its charge almost instantly. Energy weapons adore it.' }),
  P({ id: 'bat_graphene', name: 'Graphene Super-Cell', category: 'battery', rarity: 'legendary', family: 'batteries', mass: 45, hp: 100, armor: 6, value: 22000, mesh: 'battery', look: { style: 'graphene' }, faction: 'helix', stats: { batteryCap: 6000, maxDischarge: 2600 }, desc: 'Weighs nothing, stores everything.' }),
];

const FUEL: PartDef[] = [
  P({ id: 'fuel_jerry', name: 'Jerry Can Rack', category: 'fuel', rarity: 'common', mass: 25, hp: 45, armor: 2, value: 60, mesh: 'fuel', look: { style: 'jerry' }, stats: { fuelCap: 40 }, special: ['leaky'], desc: 'Three cans in a welded rack. Leaks when shot, burns when unlucky.' }),
  P({ id: 'fuel_drum', name: 'Fuel Drum', category: 'fuel', rarity: 'common', mass: 30, hp: 70, armor: 3, value: 120, mesh: 'fuel', look: { style: 'drum' }, stats: { fuelCap: 110 }, desc: 'A 110-litre oil drum strapped down with chain.' }),
  P({ id: 'fuel_armored', name: 'Armored Fuel Cell', category: 'fuel', rarity: 'uncommon', mass: 80, hp: 170, armor: 12, value: 1100, mesh: 'fuel', look: { style: 'armored' }, stats: { fuelCap: 90 }, special: ['self-sealing'], desc: 'Self-sealing bladder inside a steel box. Rarely leaks, never explodes.' }),
  P({ id: 'fuel_saddle', name: 'Saddle Tanks', category: 'fuel', rarity: 'rare', mass: 70, hp: 130, armor: 6, value: 2400, mesh: 'fuel', look: { style: 'saddle' }, stats: { fuelCap: 240 }, desc: 'Long-range tanks for crossing the whole basin.' }),
];

const COOLING: PartDef[] = [
  P({ id: 'cool_radiator', name: 'Scrap Radiator', category: 'cooling', rarity: 'common', mass: 35, hp: 50, armor: 2, value: 100, mesh: 'cooling', look: { style: 'radiator' }, stats: { cooling: 18 }, desc: 'Car radiator and a fan. Keeps small engines honest.' }),
  P({ id: 'cool_heatsink', name: 'Heat Sink Array', category: 'cooling', rarity: 'uncommon', family: 'cooling2', tech: 'cooling2', mass: 60, hp: 90, armor: 5, value: 1200, mesh: 'cooling', look: { style: 'heatsink' }, stats: { cooling: 34 }, desc: 'Copper fins in bulk. Passive and robust.' }),
  P({ id: 'cool_fans', name: 'Turbo Fan Cooler', category: 'cooling', rarity: 'rare', family: 'cooling2', tech: 'cooling2', mass: 55, hp: 60, armor: 3, value: 3000, mesh: 'cooling', look: { style: 'fans' }, stats: { cooling: 58, powerDraw: 20 }, desc: 'Twin electric fans pulling air through a dense core.' }),
  P({ id: 'cool_cryo', name: 'Cryo Cooler', category: 'cooling', rarity: 'epic', family: 'cooling2', mass: 90, hp: 90, armor: 5, value: 9000, mesh: 'cooling', look: { style: 'cryo' }, faction: 'helix', stats: { cooling: 115, powerDraw: 60 }, desc: 'Refrigerant loop cold enough to frost the hull.' }),
  P({ id: 'cool_phase', name: 'Phase-Change Heat Pipe', category: 'cooling', rarity: 'legendary', family: 'cooling2', mass: 70, hp: 120, armor: 6, value: 21000, mesh: 'cooling', look: { style: 'phase' }, stats: { cooling: 165 }, desc: 'Silent, passive, ridiculous. Pairs beautifully with a Hellfire.' }),
];

const TRANSMISSIONS: PartDef[] = [
  P({ id: 'trn_3spd', name: '3-Speed Crash Box', category: 'transmission', classes: G, rarity: 'common', mass: 55, hp: 90, armor: 4, value: 150, mesh: 'gearbox', look: { size: 0.9 }, stats: { gears: [3.1, 1.8, 1.15], finalDrive: 4.3, efficiency: 0.8, shiftTime: 0.45 }, desc: 'Three gears and a lot of grinding.' }),
  P({ id: 'trn_5spd', name: '5-Speed Manual', category: 'transmission', classes: G, rarity: 'uncommon', family: 'combustion2', tech: 'combustion2', mass: 70, hp: 110, armor: 5, value: 1300, mesh: 'gearbox', look: { size: 1 }, stats: { gears: [3.3, 2.1, 1.5, 1.15, 0.92], finalDrive: 4.1, efficiency: 0.86, shiftTime: 0.3 }, desc: 'Evenly spaced ratios for everything from climbing to cruising.' }),
  P({ id: 'trn_seq', name: 'Sequential Race Box', category: 'transmission', classes: G, rarity: 'rare', family: 'combustion2', mass: 60, hp: 100, armor: 5, value: 4000, mesh: 'gearbox', look: { size: 0.95, race: true }, stats: { gears: [3.0, 2.25, 1.75, 1.4, 1.15, 0.94], finalDrive: 4.0, efficiency: 0.93, shiftTime: 0.1 }, desc: 'Paddle-fast shifts and close ratios.' }),
  P({ id: 'trn_heavy', name: 'Heavy Torque Converter', category: 'transmission', classes: G, rarity: 'uncommon', family: 'heavyframes', mass: 150, hp: 190, armor: 8, value: 1600, mesh: 'gearbox', look: { size: 1.3 }, stats: { gears: [4.8, 2.9, 1.85, 1.3, 1.0], finalDrive: 5.4, efficiency: 0.82, shiftTime: 0.35 }, desc: 'Deep gearing for hauling tonnes up canyon walls.' }),
];

// ---------------------------------------------------------------- GROUND LOCOMOTION
const SUSPENSION: PartDef[] = [
  P({ id: 'sus_leaf', name: 'Leaf Spring Axle', category: 'suspension', classes: G, rarity: 'common', mass: 28, hp: 95, armor: 5, value: 60, mesh: 'suspension', look: { style: 'leaf' }, stats: { stiffness: 44000, damping: 3500, travel: 0.22 }, desc: 'Stiff and simple. Handles weight, hates bumps.', sockets: [sock('hub', 'hub', [0, 0.32, 0], [0, 1, 0])] }),
  P({ id: 'sus_coil', name: 'Scrap Coilover', category: 'suspension', classes: G, rarity: 'common', mass: 22, hp: 75, armor: 4, value: 80, mesh: 'suspension', look: { style: 'coil' }, stats: { stiffness: 29000, damping: 2700, travel: 0.34 }, desc: 'Spring, damper, two A-arms. The starter kit of suspension.', sockets: [sock('hub', 'hub', [0, 0.34, 0], [0, 1, 0])] }),
  P({ id: 'sus_heavy', name: 'Heavy Duty Strut', category: 'suspension', classes: G, rarity: 'uncommon', family: 'suspension2', tech: 'suspension2', mass: 55, hp: 170, armor: 8, value: 1200, mesh: 'suspension', look: { style: 'heavy' }, stats: { stiffness: 82000, damping: 6400, travel: 0.3 }, desc: 'Truck-grade strut for armour-laden builds.', sockets: [sock('hub', 'hub', [0, 0.38, 0], [0, 1, 0])] }),
  P({ id: 'sus_long', name: 'Long-Travel Racing Kit', category: 'suspension', classes: G, rarity: 'rare', family: 'suspension2', tech: 'suspension2', mass: 32, hp: 85, armor: 4, value: 2800, mesh: 'suspension', look: { style: 'long' }, stats: { stiffness: 27000, damping: 2900, travel: 0.6 }, desc: 'Sixty centimetres of travel. Jumps become landings.', sockets: [sock('hub', 'hub', [0, 0.5, 0], [0, 1, 0])] }),
  P({ id: 'sus_active', name: 'Active Hydraulic Suspension', category: 'suspension', classes: G, rarity: 'epic', family: 'suspension2', mass: 46, hp: 120, armor: 6, value: 9500, mesh: 'suspension', look: { style: 'active' }, stats: { stiffness: 52000, damping: 5000, travel: 0.5, powerDraw: 15 }, special: ['self-leveling'], desc: 'Computer-controlled struts keep the chassis flat through any corner.', sockets: [sock('hub', 'hub', [0, 0.42, 0], [0, 1, 0])] }),
];

const WHEELS: PartDef[] = [
  P({ id: 'whl_bald', name: 'Bald Tire', category: 'wheel', classes: G, rarity: 'common', mass: 22, hp: 60, armor: 2, value: 40, mesh: 'wheel', look: { tread: 'bald', rim: 'steel' }, stats: { radius: 0.4, width: 0.26, grip: 0.95, roadGrip: 1.05, sandGrip: 0.62, rockGrip: 0.85, rollResist: 0.015 }, desc: 'Tread is a rumour. Fine on asphalt, useless in sand.' }),
  P({ id: 'whl_knobby', name: 'Knobby Off-Roader', category: 'wheel', classes: G, rarity: 'common', mass: 28, hp: 72, armor: 3, value: 90, mesh: 'wheel', look: { tread: 'knobby', rim: 'steel' }, stats: { radius: 0.44, width: 0.32, grip: 1.05, roadGrip: 0.95, sandGrip: 0.95, rockGrip: 1.05, rollResist: 0.02 }, desc: 'Deep lugs that bite into dirt and sand.' }),
  P({ id: 'whl_street', name: 'Street Slick', category: 'wheel', classes: G, rarity: 'uncommon', mass: 20, hp: 55, armor: 2, value: 700, mesh: 'wheel', look: { tread: 'street', rim: 'spoke' }, stats: { radius: 0.38, width: 0.3, grip: 1.2, roadGrip: 1.3, sandGrip: 0.5, rockGrip: 0.85, rollResist: 0.012 }, desc: 'Sticky rubber for the highway. Sand turns it into a skateboard.' }),
  P({ id: 'whl_spiked', name: 'Spiked Scrap Wheel', category: 'wheel', classes: G, rarity: 'uncommon', mass: 45, hp: 95, armor: 6, value: 900, mesh: 'wheel', look: { tread: 'spiked', rim: 'solid' }, stats: { radius: 0.48, width: 0.34, grip: 1.0, roadGrip: 0.85, sandGrip: 1.05, rockGrip: 1.2, rollResist: 0.024, ramDamage: 1.5 }, desc: 'Welded spikes bite rock and shred anything alongside.' }),
  P({ id: 'whl_monster', name: 'Monster Tire', category: 'wheel', classes: G, rarity: 'rare', mass: 72, hp: 150, armor: 4, value: 3000, mesh: 'wheel', look: { tread: 'monster', rim: 'solid' }, stats: { radius: 0.72, width: 0.55, grip: 1.05, roadGrip: 0.9, sandGrip: 1.15, rockGrip: 1.1, rollResist: 0.028 }, desc: 'Enormous balloon tires that roll over wrecks. Raises your centre of mass.' }),
  P({ id: 'whl_runflat', name: 'Armored Run-Flat', category: 'wheel', classes: G, rarity: 'rare', family: 'armor2', tech: 'armor2', mass: 60, hp: 230, armor: 14, value: 3200, mesh: 'wheel', look: { tread: 'armored', rim: 'solid' }, stats: { radius: 0.46, width: 0.34, grip: 1.0, roadGrip: 1.0, sandGrip: 0.9, rockGrip: 1.0, rollResist: 0.022 }, special: ['run-flat'], desc: 'Solid-core military tire. Keeps rolling even when shredded.' }),
  P({ id: 'whl_mag', name: 'Magnetic Grip Wheel', category: 'wheel', classes: G, rarity: 'epic', family: 'energy', mass: 40, hp: 110, armor: 6, value: 9000, mesh: 'wheel', look: { tread: 'street', rim: 'mag' }, faction: 'helix', stats: { radius: 0.42, width: 0.32, grip: 1.4, roadGrip: 1.1, sandGrip: 1.0, rockGrip: 1.1, rollResist: 0.012, powerDraw: 20 }, desc: 'Electromagnetic hub that presses the tire into any surface.' }),
  P({ id: 'whl_omni', name: 'Omni-Hub Wheel', category: 'wheel', classes: G, rarity: 'legendary', family: 'energy', mass: 55, hp: 140, armor: 8, value: 24000, mesh: 'wheel', look: { tread: 'omni', rim: 'omni' }, stats: { radius: 0.44, width: 0.34, grip: 1.2, roadGrip: 1.05, sandGrip: 1.0, rockGrip: 1.05, rollResist: 0.016, powerDraw: 25 }, special: ['omni'], desc: 'Roller-studded hub that can drive sideways. Strafe in a car.' }),
];

const TRACKS: PartDef[] = [
  P({ id: 'trk_scrap', name: 'Scrap Track Unit', category: 'track', classes: G, rarity: 'uncommon', family: 'tracks', tech: 'tracks', mass: 280, hp: 340, armor: 12, value: 2400, mesh: 'track', look: { style: 'scrap' }, stats: { trackLength: 3.8, width: 0.5, radius: 0.38, grip: 1.2, roadGrip: 0.9, sandGrip: 1.3, rockGrip: 1.25, rollResist: 0.045, stiffness: 90000, damping: 8000, travel: 0.22 }, desc: 'Bulldozer tracks on a salvaged bogie frame. Goes anywhere, slowly.' }),
  P({ id: 'trk_mil', name: 'Military Track Unit', category: 'track', classes: G, rarity: 'rare', family: 'tracks', tech: 'tracks', mass: 400, hp: 500, armor: 20, value: 6200, mesh: 'track', look: { style: 'mil' }, faction: 'authority', stats: { trackLength: 4.6, width: 0.62, radius: 0.42, grip: 1.35, roadGrip: 1.0, sandGrip: 1.35, rockGrip: 1.3, rollResist: 0.04, stiffness: 130000, damping: 11000, travel: 0.26 }, desc: 'Torsion-bar tank tracks with rubber pads.' }),
];

const GROUND_MISC: PartDef[] = [
  P({ id: 'bst_nitro', name: 'Nitrous Canister', category: 'booster', classes: G, rarity: 'uncommon', mass: 30, hp: 40, armor: 2, value: 900, mesh: 'booster', look: { style: 'nitro' }, stats: { thrust: 0, boostTime: 5, torque: 0.7 }, special: ['nitro', 'explosive'], desc: 'Adds 70% engine torque while boosting. Explodes if punctured.' }),
  P({ id: 'bst_rocket', name: 'Rocket Booster', category: 'booster', classes: ['ground', 'mech'], rarity: 'rare', family: 'rocketry', tech: 'rocketry', mass: 75, hp: 75, armor: 4, value: 3400, mesh: 'booster', look: { style: 'rocket' }, tiltable: true, stats: { thrust: 15000, boostTime: 3.2, heat: 14 }, desc: 'Solid rocket motor. Point the nozzle away from the direction you want to go.' }),
  P({ id: 'ram_bullbar', name: 'Bull Bar', category: 'ram', classes: G, rarity: 'common', mass: 45, hp: 170, armor: 10, value: 120, mesh: 'ram', look: { style: 'bullbar' }, stats: { ramDamage: 1.4, ramArmor: 0.5 }, desc: 'Pipe bumper. Protects the front and dents the other guy.' }),
  P({ id: 'ram_spike', name: 'Spike Ram', category: 'ram', classes: G, rarity: 'uncommon', mass: 85, hp: 210, armor: 12, value: 900, mesh: 'ram', look: { style: 'spike' }, stats: { ramDamage: 2.1, ramArmor: 0.45 }, desc: 'Sharpened rebar welded into a grin.' }),
  P({ id: 'ram_plow', name: 'Plow Blade', category: 'ram', classes: G, rarity: 'rare', family: 'heavyframes', mass: 230, hp: 440, armor: 22, value: 3500, mesh: 'ram', look: { style: 'plow' }, stats: { ramDamage: 2.6, ramArmor: 0.3 }, desc: 'Snowplough blade. Shoves vehicles aside and shrugs off gunfire.' }),
  P({ id: 'ram_saw', name: 'Buzzsaw Rig', category: 'ram', classes: G, rarity: 'epic', mass: 160, hp: 190, armor: 10, value: 9000, mesh: 'ram', look: { style: 'saw' }, stats: { ramDamage: 3.0, ramArmor: 0.5, damage: 90, pen: 30, reach: 1.6, powerDraw: 40, melee: 'saw' }, special: ['grinder'], desc: 'Spinning saw blade that grinds through anything it touches.' }),
  P({ id: 'crg_rack', name: 'Cargo Rack', category: 'cargo', rarity: 'common', mass: 30, hp: 60, armor: 3, value: 80, mesh: 'cargo', look: { style: 'rack' }, stats: { cargo: 250 }, desc: 'A welded basket. Holds salvage, mostly.' }),
  P({ id: 'crg_crate', name: 'Storage Crate', category: 'cargo', rarity: 'uncommon', mass: 70, hp: 120, armor: 6, value: 600, mesh: 'cargo', look: { style: 'crate' }, stats: { cargo: 520 }, desc: 'Lockable steel box for valuable parts.' }),
  P({ id: 'crg_bay', name: 'Salvage Bay', category: 'cargo', classes: G, rarity: 'rare', mass: 150, hp: 190, armor: 8, value: 3000, mesh: 'cargo', look: { style: 'bay' }, stats: { cargo: 1300 }, special: ['fast salvage'], desc: 'Hydraulic cargo bay with a winch. Strips wrecks 30% faster.' }),
  P({ id: 'crg_pod', name: 'Cargo Pod', category: 'cargo', classes: ['air', 'mech'], rarity: 'uncommon', mass: 40, hp: 70, armor: 4, value: 700, mesh: 'cargo', look: { style: 'pod' }, stats: { cargo: 320 }, desc: 'Streamlined underslung pod.' }),
];

// ---------------------------------------------------------------- ARMOR & UTILITY
const ARMOR: PartDef[] = [
  P({ id: 'arm_scrap_s', name: 'Scrap Plate (S)', category: 'armor', rarity: 'common', mass: 30, hp: 95, armor: 6, value: 30, mesh: 'armor', look: { style: 'scrap', w: 0.6, h: 0.5, t: 0.05 }, tiltable: true, desc: 'A car door, more or less.' }),
  P({ id: 'arm_scrap_l', name: 'Scrap Plate (L)', category: 'armor', rarity: 'common', mass: 55, hp: 160, armor: 6, value: 55, mesh: 'armor', look: { style: 'scrap', w: 1.0, h: 0.7, t: 0.05 }, tiltable: true, desc: 'A welded patchwork of sheet steel.' }),
  P({ id: 'arm_steel_s', name: 'Steel Plate (S)', category: 'armor', rarity: 'uncommon', family: 'armor2', tech: 'armor2', mass: 45, hp: 140, armor: 12, value: 300, mesh: 'armor', look: { style: 'steel', w: 0.6, h: 0.5, t: 0.06 }, tiltable: true, desc: 'Rolled steel with proper bolts.' }),
  P({ id: 'arm_steel_l', name: 'Steel Plate (L)', category: 'armor', rarity: 'uncommon', family: 'armor2', tech: 'armor2', mass: 85, hp: 230, armor: 12, value: 520, mesh: 'armor', look: { style: 'steel', w: 1.0, h: 0.7, t: 0.06 }, tiltable: true, desc: 'Heavy panel that stops rifle rounds cold.' }),
  P({ id: 'arm_sloped', name: 'Sloped Glacis Plate', category: 'armor', rarity: 'rare', family: 'armor2', tech: 'armor2', mass: 115, hp: 270, armor: 17, value: 1800, mesh: 'armor', look: { style: 'sloped', w: 1.1, h: 0.8, t: 0.08 }, tiltable: true, special: ['ricochet'], desc: 'Angled armour: light rounds glance off entirely.' }),
  P({ id: 'arm_composite', name: 'Composite Panel', category: 'armor', rarity: 'rare', family: 'composite', tech: 'composite', mass: 60, hp: 250, armor: 22, value: 2800, mesh: 'armor', look: { style: 'composite', w: 0.9, h: 0.6, t: 0.07 }, tiltable: true, desc: 'Ceramic-steel sandwich. Half the weight of steel, twice the protection.' }),
  P({ id: 'arm_reactive', name: 'Reactive Armor Block', category: 'armor', rarity: 'epic', family: 'composite', mass: 70, hp: 130, armor: 14, value: 6000, mesh: 'armor', look: { style: 'reactive', w: 0.7, h: 0.5, t: 0.12 }, tiltable: true, stats: { reactive: true }, special: ['reactive'], desc: 'Explodes outward to cancel the next heavy hit completely. Single use.' }),
  P({ id: 'arm_ceramic', name: 'Ablative Ceramic Tiles', category: 'armor', rarity: 'epic', family: 'composite', mass: 42, hp: 210, armor: 27, value: 7500, mesh: 'armor', look: { style: 'ceramic', w: 0.8, h: 0.6, t: 0.05 }, tiltable: true, faction: 'helix', desc: 'Featherweight tiles that shrug off almost anything.' }),
  P({ id: 'arm_aegis', name: 'Aegis Hard-Light Emitter', category: 'armor', rarity: 'exotic', family: 'energy', mass: 55, hp: 420, armor: 30, value: 48000, mesh: 'armor', look: { style: 'aegis', w: 1.0, h: 0.7, t: 0.08 }, tiltable: true, unique: true, faction: 'helix', stats: { powerDraw: 90, repairRate: 40 }, special: ['regenerates'], desc: 'Projects a panel of hard light that regenerates using power instead of breaking.' }),
  P({ id: 'sen_scanner', name: 'Scanner Dish', category: 'sensor', rarity: 'uncommon', mass: 20, hp: 40, armor: 2, value: 400, mesh: 'sensor', look: { style: 'dish' }, stats: { scanRange: 320, powerDraw: 5 }, desc: 'Reads component condition and rarity at long range.' }),
  P({ id: 'sen_radar', name: 'Radar Mast', category: 'sensor', rarity: 'rare', family: 'radar', tech: 'radar', mass: 45, hp: 60, armor: 3, value: 3500, mesh: 'sensor', look: { style: 'radar' }, stats: { radarRange: 650, scanRange: 380, powerDraw: 15 }, desc: 'Rotating radar. Shows every machine within 650 m on your compass.' }),
  P({ id: 'sen_jammer', name: 'EW Jammer', category: 'sensor', rarity: 'epic', family: 'ew', tech: 'ew', mass: 50, hp: 60, armor: 3, value: 8000, mesh: 'sensor', look: { style: 'jammer' }, stats: { jammer: 0.65, powerDraw: 40 }, desc: 'Breaks missile locks and scrambles enemy targeting.' }),
  P({ id: 'cm_flares', name: 'Flare Dispenser', category: 'countermeasure', rarity: 'uncommon', family: 'ew', mass: 25, hp: 40, armor: 3, value: 800, mesh: 'flares', stats: { flares: 12 }, desc: 'Pops decoy flares automatically when missiles lock on.' }),
  P({ id: 'lgt_bar', name: 'Scrap Light Bar', category: 'light', rarity: 'common', mass: 12, hp: 30, armor: 2, value: 40, mesh: 'lights', look: { style: 'bar' }, stats: { lightRange: 60 }, desc: 'Four headlamps on a rail. Night becomes merely dark.' }),
  P({ id: 'lgt_spot', name: 'Searchlight', category: 'light', rarity: 'uncommon', mass: 25, hp: 40, armor: 3, value: 300, mesh: 'lights', look: { style: 'spot' }, stats: { lightRange: 130, powerDraw: 3 }, desc: 'Powerful swivel searchlight that follows your aim.' }),
  P({ id: 'stb_gyro', name: 'Gyro Stabilizer', category: 'stabilizer', rarity: 'common', mass: 30, hp: 55, armor: 3, value: 200, mesh: 'gyro', look: { size: 1 }, stats: { torqueAuthority: 2200, powerDraw: 12 }, desc: 'Spinning flywheel that fights unwanted rotation. Aircraft need it; cars land better with it.' }),
  P({ id: 'stb_gyro_mil', name: 'Military Gyro', category: 'stabilizer', rarity: 'rare', family: 'rotors2', mass: 45, hp: 90, armor: 6, value: 3000, mesh: 'gyro', look: { size: 1.3 }, stats: { torqueAuthority: 7000, powerDraw: 35 }, desc: 'Triple-axis control moment gyro.' }),
];

// ---------------------------------------------------------------- WEAPONS
const WEAPONS: PartDef[] = [
  P({ id: 'wpn_lmg', name: 'Rattler LMG', category: 'weapon', rarity: 'common', mass: 40, hp: 70, armor: 4, value: 180, mesh: 'w_mg', look: { barrels: 1 }, tiltable: true, stats: { weapon: 'mg', damage: 9, pen: 3, rof: 11, projSpeed: 650, spread: 1.1, range: 380, recoil: 22, ammo: 800, heat: 0.35, yawLimit: 180, pitchMin: -15, pitchMax: 60, turnRate: 4 }, desc: 'Belt-fed light machine gun. Chews exposed parts, plinks off armour.' }),
  P({ id: 'wpn_twinlmg', name: 'Twin Rattlers', category: 'weapon', rarity: 'uncommon', mass: 72, hp: 90, armor: 5, value: 800, mesh: 'w_mg', look: { barrels: 2 }, tiltable: true, stats: { weapon: 'mg', damage: 9, pen: 3, rof: 19, projSpeed: 650, spread: 1.3, range: 380, recoil: 22, ammo: 1400, heat: 0.33, yawLimit: 180, pitchMin: -15, pitchMax: 60, turnRate: 3.6, barrels: 2 }, desc: 'Two Rattlers on one mount. Twice the noise.' }),
  P({ id: 'wpn_chaingun', name: 'Chaingun', category: 'weapon', rarity: 'uncommon', family: 'ballistics2', mass: 110, hp: 115, armor: 6, value: 1600, mesh: 'w_chaingun', tiltable: true, stats: { weapon: 'chaingun', damage: 8, pen: 4, rof: 24, spinUp: 0.7, projSpeed: 700, spread: 1.6, range: 420, recoil: 18, ammo: 2000, heat: 0.3, yawLimit: 180, pitchMin: -15, pitchMax: 55, turnRate: 3 }, desc: 'Six rotating barrels. Spin it up, hold it down.' }),
  P({ id: 'wpn_hmg', name: 'Twin .50 HMG', category: 'weapon', rarity: 'rare', family: 'ballistics2', tech: 'ballistics2', mass: 140, hp: 135, armor: 8, value: 3800, mesh: 'w_hmg', tiltable: true, stats: { weapon: 'mg', damage: 17, pen: 9, rof: 10, projSpeed: 820, spread: 0.8, range: 540, recoil: 55, ammo: 900, heat: 0.5, yawLimit: 180, pitchMin: -12, pitchMax: 65, turnRate: 2.8, barrels: 2 }, desc: 'Heavy machine guns that punch through light plate.' }),
  P({ id: 'wpn_shotgun', name: 'Scrap Scattergun', category: 'weapon', rarity: 'common', mass: 55, hp: 70, armor: 4, value: 250, mesh: 'w_shotgun', tiltable: true, stats: { weapon: 'shotgun', damage: 9, pellets: 9, pen: 4, rof: 1.3, projSpeed: 420, spread: 5.5, range: 70, recoil: 380, ammo: 120, heat: 1.5, yawLimit: 150, pitchMin: -15, pitchMax: 40, turnRate: 3.2 }, desc: 'Sawn-off pipe cannon. Devastating up close.' }),
  P({ id: 'wpn_autocannon', name: '20mm Autocannon', category: 'weapon', rarity: 'uncommon', family: 'ballistics2', tech: 'ballistics2', mass: 190, hp: 160, armor: 8, value: 2600, mesh: 'w_autocannon', tiltable: true, stats: { weapon: 'autocannon', damage: 38, pen: 14, splash: 1.6, splashDamage: 12, rof: 4, projSpeed: 600, spread: 0.5, range: 620, recoil: 420, ammo: 300, heat: 2, yawLimit: 180, pitchMin: -10, pitchMax: 55, turnRate: 2.2 }, desc: 'Explosive cannon rounds that crack plating open.' }),
  P({ id: 'wpn_bushmaster', name: '30mm Bushmaster', category: 'weapon', rarity: 'rare', family: 'ballistics2', mass: 300, hp: 210, armor: 12, value: 6500, mesh: 'w_autocannon', look: { big: true }, tiltable: true, faction: 'authority', stats: { weapon: 'autocannon', damage: 65, pen: 22, splash: 2, splashDamage: 22, rof: 3, projSpeed: 650, spread: 0.4, range: 700, recoil: 800, ammo: 200, heat: 2.6, yawLimit: 180, pitchMin: -10, pitchMax: 50, turnRate: 1.8 }, desc: 'Chain-driven armour breaker from an Authority IFV.' }),
  P({ id: 'wpn_cannon', name: '75mm Field Cannon', category: 'weapon', rarity: 'rare', family: 'heavyordnance', tech: 'heavyordnance', mass: 420, hp: 250, armor: 14, value: 7000, mesh: 'w_cannon', tiltable: true, stats: { weapon: 'cannon', damage: 190, pen: 32, splash: 3.5, splashDamage: 70, rof: 0.45, projSpeed: 380, spread: 0.25, range: 850, recoil: 5200, ammo: 40, heat: 8, yawLimit: 180, pitchMin: -8, pitchMax: 40, turnRate: 1.3 }, special: ['massive recoil'], desc: 'Artillery piece on a turret ring. Mount it on something heavy — the recoil is brutal.' }),
  P({ id: 'wpn_thunder', name: 'Thunder 120mm Cannon', category: 'weapon', rarity: 'epic', family: 'heavyordnance', mass: 950, hp: 390, armor: 22, value: 16000, mesh: 'w_cannon', look: { big: true }, tiltable: true, faction: 'authority', stats: { weapon: 'cannon', damage: 420, pen: 60, splash: 5, splashDamage: 150, rof: 0.25, projSpeed: 460, spread: 0.2, range: 1000, recoil: 13000, ammo: 24, heat: 15, yawLimit: 180, pitchMin: -6, pitchMax: 35, turnRate: 0.9 }, special: ['massive recoil'], desc: 'Main battle tank gun. Will flip anything under five tonnes when it fires.' }),
  P({ id: 'wpn_rockets', name: 'Scrap Rocket Pod', category: 'weapon', rarity: 'uncommon', family: 'rocketry', tech: 'rocketry', mass: 90, hp: 80, armor: 4, value: 1800, mesh: 'w_rockets', tiltable: true, stats: { weapon: 'rockets', damage: 70, pen: 12, splash: 4, splashDamage: 40, rof: 5, magazine: 8, reload: 5, projSpeed: 110, spread: 2.5, range: 500, recoil: 60, ammo: 64, heat: 1.5, yawLimit: 120, pitchMin: -10, pitchMax: 45, turnRate: 2.4 }, desc: 'Eight unguided rockets. Ripple-fire and hope.' }),
  P({ id: 'wpn_missiles', name: 'Hydra Missile Rack', category: 'weapon', rarity: 'rare', family: 'guided', tech: 'guided', mass: 120, hp: 100, armor: 5, value: 5500, mesh: 'w_missiles', tiltable: true, stats: { weapon: 'missiles', damage: 120, pen: 20, splash: 4, splashDamage: 55, rof: 2, magazine: 4, reload: 7, projSpeed: 95, lockTime: 1.4, turnRateMissile: 2.4, range: 900, recoil: 40, ammo: 24, heat: 1, yawLimit: 90, pitchMin: -5, pitchMax: 45, turnRate: 2 }, desc: 'Lock onto a specific component and let the missile do the rest.' }),
  P({ id: 'wpn_swarm', name: 'Swarm Launcher', category: 'weapon', rarity: 'epic', family: 'guided', mass: 180, hp: 120, armor: 6, value: 14000, mesh: 'w_missiles', look: { swarm: true }, tiltable: true, stats: { weapon: 'missiles', damage: 45, pen: 14, splash: 2.5, splashDamage: 20, rof: 10, magazine: 16, reload: 9, projSpeed: 120, lockTime: 1.0, turnRateMissile: 3.6, range: 750, recoil: 15, ammo: 96, heat: 0.5, yawLimit: 90, pitchMin: -5, pitchMax: 50, turnRate: 2 }, desc: 'Sixteen micro-missiles that spread across every component of a target.' }),
  P({ id: 'wpn_laser', name: 'Pulse Laser', category: 'weapon', rarity: 'rare', family: 'energy', tech: 'energy', mass: 70, hp: 85, armor: 5, value: 7000, mesh: 'w_laser', tiltable: true, faction: 'helix', stats: { weapon: 'laser', damage: 24, pen: 12, rof: 5, energyPerShot: 9, range: 650, recoil: 0, heat: 1.4, yawLimit: 180, pitchMin: -20, pitchMax: 70, turnRate: 4 }, desc: 'Hitscan pulses powered by your electrical grid. No ammo, no recoil.' }),
  P({ id: 'wpn_beam', name: 'Lance Beam Laser', category: 'weapon', rarity: 'epic', family: 'energy', tech: 'energy', mass: 120, hp: 100, armor: 6, value: 15000, mesh: 'w_laser', look: { beam: true }, tiltable: true, faction: 'helix', stats: { weapon: 'beam', damage: 110, pen: 18, energyPerShot: 120, range: 700, recoil: 0, heat: 12, yawLimit: 180, pitchMin: -20, pitchMax: 70, turnRate: 3 }, desc: 'Continuous cutting beam. Slices components apart while you hold the trigger.' }),
  P({ id: 'wpn_railgun', name: 'Gauss Railgun', category: 'weapon', rarity: 'legendary', family: 'energy', mass: 380, hp: 170, armor: 10, value: 32000, blueprint: true, mesh: 'w_railgun', tiltable: true, stats: { weapon: 'railgun', damage: 560, pen: 90, rof: 0.4, chargeTime: 1.1, energyPerShot: 420, range: 1400, recoil: 3600, heat: 20, yawLimit: 180, pitchMin: -8, pitchMax: 45, turnRate: 1.4 }, special: ['piercing'], desc: 'Magnetic slug that punches through every component in a line. Needs a capacitor to fire.' }),
  P({ id: 'wpn_flamer', name: 'Scrap Flamethrower', category: 'weapon', rarity: 'uncommon', family: 'rocketry', mass: 80, hp: 80, armor: 4, value: 1500, mesh: 'w_flamer', tiltable: true, stats: { weapon: 'flamer', damage: 45, pen: 8, range: 28, fuelUse: 1.2, heat: 3, recoil: 0, yawLimit: 150, pitchMin: -15, pitchMax: 40, turnRate: 3 }, special: ['ignites'], desc: 'Sprays burning fuel from your own tanks. Sets components on fire.' }),
  P({ id: 'wpn_arc', name: 'Tesla Arc Projector', category: 'weapon', rarity: 'exotic', family: 'energy', mass: 110, hp: 140, armor: 8, value: 48000, unique: true, faction: 'helix', mesh: 'w_arc', tiltable: true, stats: { weapon: 'arc', damage: 60, pen: 999, rof: 2, energyPerShot: 60, range: 130, recoil: 0, heat: 5, yawLimit: 180, pitchMin: -20, pitchMax: 60, turnRate: 3 }, special: ['ignores armor', 'chains'], desc: 'Lightning that ignores armour and jumps from component to component — and machine to machine.' }),
];

// ---------------------------------------------------------------- AIR
const AIR: PartDef[] = [
  P({ id: 'rot_scrap', name: 'Scrap Rotor', category: 'rotor', classes: A, rarity: 'common', mass: 24, hp: 50, armor: 2, value: 150, mesh: 'rotor', look: { style: 'scrap', blades: 2 }, tiltable: true, stats: { radius: 0.95, thrust: 3100, powerDraw: 40, cyclic: 0.12, reaction: 0.05, spin: 1 }, desc: 'Two blades cut from a ceiling fan the size of a car. Light, fragile, loud.' }),
  P({ id: 'rot_ducted', name: 'Ducted Fan', category: 'rotor', classes: A, rarity: 'uncommon', family: 'rotors2', tech: 'rotors2', mass: 42, hp: 120, armor: 8, value: 1400, mesh: 'rotor', look: { style: 'ducted', blades: 7 }, tiltable: true, stats: { radius: 0.7, thrust: 3500, powerDraw: 60, cyclic: 0.14, reaction: 0.04, spin: 1 }, special: ['shrouded'], desc: 'Fan inside an armoured shroud. Survives hits and rotor strikes.' }),
  P({ id: 'rot_main', name: 'Main Rotor Assembly', category: 'rotor', classes: A, rarity: 'uncommon', family: 'rotors2', tech: 'rotors2', mass: 150, hp: 170, armor: 6, value: 2600, mesh: 'rotor', look: { style: 'main', blades: 4 }, tiltable: true, stats: { radius: 4.0, thrust: 22000, powerDraw: 300, cyclic: 0.4, reaction: 0.09, spin: 1 }, desc: 'Full-size helicopter rotor with cyclic control. Needs a tail rotor to cancel its torque.' }),
  P({ id: 'rot_coax', name: 'Coaxial Rotor Stack', category: 'rotor', classes: A, rarity: 'rare', family: 'rotors2', tech: 'rotors2', mass: 195, hp: 190, armor: 7, value: 6800, mesh: 'rotor', look: { style: 'coax', blades: 3 }, tiltable: true, stats: { radius: 3.5, thrust: 28000, powerDraw: 380, cyclic: 0.4, reaction: 0, spin: 1 }, desc: 'Counter-rotating rotors: huge lift and no torque to cancel.' }),
  P({ id: 'rot_tilt', name: 'Tiltrotor Nacelle', category: 'rotor', classes: A, rarity: 'epic', family: 'vector', tech: 'vector', mass: 165, hp: 160, armor: 8, value: 11000, mesh: 'rotor', look: { style: 'tilt', blades: 3 }, tiltable: true, stats: { radius: 2.1, thrust: 12500, powerDraw: 190, cyclic: 0.22, reaction: 0.02, spin: 1, gimbal: 1.2 }, special: ['tilts forward'], desc: 'Swivelling prop-rotor. Tilts forward at speed for aeroplane-fast cruising.' }),
  P({ id: 'rot_prop', name: 'Pusher Propeller', category: 'rotor', classes: A, rarity: 'common', mass: 35, hp: 60, armor: 3, value: 180, mesh: 'rotor', look: { style: 'prop', blades: 3 }, tiltable: true, stats: { radius: 1.0, thrust: 2800, powerDraw: 45, cyclic: 0, reaction: 0.03, spin: 1 }, desc: 'Mount it facing backwards on a tail for forward thrust.' }),
  P({ id: 'jet_pulse', name: 'Scrap Pulsejet', category: 'jet', classes: A, rarity: 'uncommon', family: 'rocketry', mass: 60, hp: 70, armor: 3, value: 1200, mesh: 'jet', look: { style: 'pulse' }, tiltable: true, stats: { thrust: 5200, fuelUse: 2.6, heat: 12 }, desc: 'A tube that explodes fifty times a second. Deafening, cheap, effective.' }),
  P({ id: 'jet_turbo', name: 'Turbojet', category: 'jet', classes: A, rarity: 'rare', family: 'turbines', tech: 'turbines', mass: 140, hp: 125, armor: 5, value: 5000, mesh: 'jet', look: { style: 'turbo' }, tiltable: true, stats: { thrust: 12500, fuelUse: 4.2, heat: 18 }, desc: 'Real jet engine. Burns fuel like it is going out of style.' }),
  P({ id: 'jet_lift', name: 'Lift Jet', category: 'jet', classes: A, rarity: 'rare', family: 'turbines', tech: 'turbines', mass: 95, hp: 100, armor: 5, value: 4600, mesh: 'jet', look: { style: 'lift' }, tiltable: true, stats: { thrust: 9500, fuelUse: 3.6, heat: 14 }, desc: 'Short vertical-thrust turbine for VTOL builds.' }),
  P({ id: 'jet_vector', name: 'Hornet VX Vector Thruster', category: 'jet', classes: A, rarity: 'legendary', family: 'vector', mass: 110, hp: 140, armor: 6, value: 30000, blueprint: true, mesh: 'jet', look: { style: 'vector' }, tiltable: true, stats: { thrust: 15500, gimbal: 0.65, powerDraw: 540, heat: 10 }, special: ['vectored thrust'], desc: 'Gimballed electric thruster: superb aerial strafing and instant response — but it drinks enormous power.' }),
  P({ id: 'wng_scrap', name: 'Scrap Wing', category: 'wing', classes: A, rarity: 'common', mass: 40, hp: 85, armor: 3, value: 150, mesh: 'wing', look: { style: 'scrap', span: 2.2, chord: 1.0 }, tiltable: true, stats: { wingArea: 2.2, liftCoef: 0.85, drag: 0.05 }, desc: 'Sheet-metal wing. Adds lift at speed so your rotors can relax.' }),
  P({ id: 'wng_stub', name: 'Stub Wing Pylon', category: 'wing', classes: A, rarity: 'uncommon', mass: 45, hp: 120, armor: 5, value: 700, mesh: 'wing', look: { style: 'stub', span: 1.2, chord: 0.8 }, tiltable: true, stats: { wingArea: 0.9, liftCoef: 0.6, drag: 0.04 }, sockets: [sock('pylon_a', 'hardpoint', [0.1, 0.45, 0], [1, 0, 0], { forward: [0, 0, -1], label: 'Pylon Inner' }), sock('pylon_b', 'hardpoint', [0.1, 0.95, 0], [1, 0, 0], { forward: [0, 0, -1], label: 'Pylon Outer' })], desc: 'Short wing with two weapon pylons underneath.' }),
  P({ id: 'wng_swept', name: 'Swept Wing', category: 'wing', classes: A, rarity: 'rare', family: 'aero', tech: 'aero', mass: 85, hp: 150, armor: 5, value: 3800, mesh: 'wing', look: { style: 'swept', span: 3.2, chord: 1.4 }, tiltable: true, stats: { wingArea: 4.8, liftCoef: 1.1, drag: 0.04 }, desc: 'Proper aerofoil. Fast forward flight becomes nearly free.' }),
  P({ id: 'stb_fin', name: 'Tail Fin', category: 'stabilizer', classes: A, rarity: 'common', mass: 15, hp: 45, armor: 2, value: 90, mesh: 'fin', tiltable: true, stats: { wingArea: 0.7, torqueAuthority: 0 }, special: ['weathervane'], desc: 'Passive stability: keeps the nose pointed into the wind at speed.' }),
  P({ id: 'gear_skids', name: 'Landing Skids', category: 'gear', classes: A, rarity: 'common', mass: 35, hp: 95, armor: 4, value: 90, mesh: 'gear', look: { style: 'skids' }, desc: 'Two bent pipes. Land on these rather than your rotors.' }),
  P({ id: 'gear_wheels', name: 'Wheeled Landing Gear', category: 'gear', classes: A, rarity: 'uncommon', mass: 60, hp: 110, armor: 5, value: 700, mesh: 'gear', look: { style: 'wheels' }, desc: 'Sprung gear with tyres for rolling landings.' }),
  P({ id: 'brk_air', name: 'Air Brake', category: 'airbrake', classes: A, rarity: 'uncommon', family: 'aero', mass: 30, hp: 60, armor: 3, value: 800, mesh: 'airbrake', stats: { drag: 0.9 }, desc: 'Deploys when you slow down, killing speed fast for tight turns.' }),
];

// ---------------------------------------------------------------- MECH
const legSockets = (thigh: number, shin: number) => [
  sock('hipjoint', 'joint', [0, 0, 0], [1, 0, 0], { label: 'Hip Joint' }),
  sock('kneejoint', 'joint', [0, thigh, 0], [1, 0, 0], { label: 'Knee Joint' }),
  sock('foot', 'foot', [0, thigh + shin, 0], [0, -1, 0], { forward: [0, 0, -1], label: 'Foot' }),
];

const MECH: PartDef[] = [
  P({ id: 'leg_stilt', name: 'Stilt Leg', category: 'leg', classes: M, rarity: 'common', mass: 190, hp: 230, armor: 10, value: 300, mesh: 'leg', look: { style: 'stilt' }, stats: { thigh: 1.3, shin: 1.4, loadRating: 2600, stride: 1.5, stepTime: 0.38 }, sockets: legSockets(1.3, 1.4), desc: 'Tall, thin, quick. Needs hip and knee actuators and a foot.' }),
  P({ id: 'leg_strider', name: 'Strider Leg', category: 'leg', classes: M, rarity: 'uncommon', family: 'hydraulics2', tech: 'hydraulics2', mass: 260, hp: 320, armor: 14, value: 1400, mesh: 'leg', look: { style: 'strider' }, stats: { thigh: 1.5, shin: 1.6, loadRating: 3700, stride: 1.9, stepTime: 0.4 }, sockets: legSockets(1.5, 1.6), desc: 'Balanced leg with armoured shins.' }),
  P({ id: 'leg_raptor', name: 'Raptor Leg', category: 'leg', classes: M, rarity: 'rare', family: 'hydraulics2', mass: 230, hp: 270, armor: 12, value: 4200, mesh: 'leg', look: { style: 'raptor', digitigrade: true }, stats: { thigh: 1.4, shin: 1.8, loadRating: 3100, stride: 2.5, stepTime: 0.3 }, sockets: legSockets(1.4, 1.8), desc: 'Reverse-jointed sprinting leg. The fastest walker design known.' }),
  P({ id: 'leg_crab', name: 'Crab Leg', category: 'leg', classes: M, rarity: 'uncommon', family: 'hydraulics2', mass: 220, hp: 270, armor: 12, value: 1500, mesh: 'leg', look: { style: 'crab', spider: true }, stats: { thigh: 1.6, shin: 1.7, loadRating: 2900, stride: 1.6, stepTime: 0.34 }, sockets: legSockets(1.6, 1.7), desc: 'Splayed insect-style leg for four-legged walkers. Superb on slopes.' }),
  P({ id: 'leg_walker', name: 'Hydraulic Walker Leg', category: 'leg', classes: M, rarity: 'rare', family: 'heavyjoints', tech: 'heavyjoints', mass: 480, hp: 540, armor: 20, value: 5000, mesh: 'leg', look: { style: 'walker' }, stats: { thigh: 1.7, shin: 1.8, loadRating: 6800, stride: 2.0, stepTime: 0.55 }, sockets: legSockets(1.7, 1.8), desc: 'Industrial walker leg rated for five tonnes.' }),
  P({ id: 'leg_titan', name: 'Titan Leg', category: 'leg', classes: M, rarity: 'epic', family: 'heavyjoints', mass: 820, hp: 920, armor: 30, value: 14000, mesh: 'leg', look: { style: 'titan' }, faction: 'authority', stats: { thigh: 2.1, shin: 2.3, loadRating: 12500, stride: 2.8, stepTime: 0.6 }, sockets: legSockets(2.1, 2.3), desc: 'Assault-mech leg. Every step shakes the ground.' }),
  P({ id: 'act_scrap', name: 'Scrap Hydraulic Joint', category: 'actuator', classes: M, rarity: 'common', mass: 45, hp: 115, armor: 6, value: 120, mesh: 'actuator', look: { style: 'scrap' }, stats: { jointStrength: 1.0, jointSpeed: 1.0, powerDraw: 18 }, desc: 'Leaky hydraulic ram. Does the job.' }),
  P({ id: 'act_servo', name: 'Servo Actuator', category: 'actuator', classes: M, rarity: 'uncommon', family: 'hydraulics2', tech: 'hydraulics2', mass: 40, hp: 115, armor: 6, value: 1000, mesh: 'actuator', look: { style: 'servo' }, stats: { jointStrength: 1.05, jointSpeed: 1.3, powerDraw: 26 }, desc: 'Electric servo: faster steps, same strength.' }),
  P({ id: 'act_heavy', name: 'Heavy Hydraulic Ram', category: 'actuator', classes: M, rarity: 'rare', family: 'heavyjoints', tech: 'heavyjoints', mass: 90, hp: 210, armor: 12, value: 3200, mesh: 'actuator', look: { style: 'heavy' }, stats: { jointStrength: 1.6, jointSpeed: 0.9, powerDraw: 42 }, desc: 'Double-acting ram. Carries much heavier builds.' }),
  P({ id: 'act_titan', name: 'Titan Joint', category: 'actuator', classes: M, rarity: 'legendary', family: 'heavyjoints', mass: 110, hp: 270, armor: 16, value: 28000, blueprint: true, mesh: 'actuator', look: { style: 'titan' }, stats: { jointStrength: 2.4, jointSpeed: 1.6, powerDraw: 230 }, special: ['power hungry'], desc: 'Moves extremely heavy limbs at high speed — but requires a powerful generator.' }),
  P({ id: 'act_excavator', name: 'Excavator Mega-Joint', category: 'actuator', classes: M, rarity: 'legendary', family: 'heavyjoints', mass: 200, hp: 480, armor: 22, value: 34000, unique: true, mesh: 'actuator', look: { style: 'mega' }, stats: { jointStrength: 3.0, jointSpeed: 1.0, powerDraw: 150 }, desc: 'Torn from the Excavator itself. Absurd strength for any walker brave enough to carry it.' }),
  P({ id: 'ft_pad', name: 'Pad Foot', category: 'foot', classes: M, rarity: 'common', mass: 40, hp: 95, armor: 8, value: 60, mesh: 'foot', look: { style: 'pad' }, stats: { footGrip: 1.0, footSize: 0.6 }, desc: 'Flat steel pad.' }),
  P({ id: 'ft_claw', name: 'Claw Foot', category: 'foot', classes: M, rarity: 'uncommon', mass: 55, hp: 115, armor: 9, value: 800, mesh: 'foot', look: { style: 'claw' }, stats: { footGrip: 1.35, footSize: 0.55 }, desc: 'Three talons for gripping rock and slopes.' }),
  P({ id: 'ft_wide', name: 'Snowshoe Foot', category: 'foot', classes: M, rarity: 'uncommon', mass: 70, hp: 125, armor: 8, value: 900, mesh: 'foot', look: { style: 'wide' }, stats: { footGrip: 1.1, footSize: 0.95 }, special: ['sand walker'], desc: 'Broad foot that will not sink into sand.' }),
  P({ id: 'ft_mag', name: 'Mag-Lock Foot', category: 'foot', classes: M, rarity: 'epic', family: 'energy', mass: 60, hp: 130, armor: 10, value: 8500, mesh: 'foot', look: { style: 'mag' }, faction: 'helix', stats: { footGrip: 1.8, footSize: 0.6, powerDraw: 10 }, special: ['climber'], desc: 'Electromagnetic grip — walks up slopes that stop everything else.' }),
  P({ id: 'arm_light', name: 'Light Manipulator Arm', category: 'arm', classes: M, rarity: 'common', mass: 110, hp: 170, armor: 8, value: 150, mesh: 'arm', look: { style: 'light' }, stats: { loadRating: 260, turnRate: 2.4, armLength: 1.3 }, sockets: [sock('hand', 'hand', [-0.1, 0.45, -1.2], [-1, 0, 0], { label: 'Hand Mount' })], desc: 'Carries light weapons or tools with good speed.' }),
  P({ id: 'arm_industrial', name: 'Industrial Arm', category: 'arm', classes: M, rarity: 'uncommon', mass: 180, hp: 270, armor: 12, value: 1300, mesh: 'arm', look: { style: 'industrial' }, stats: { loadRating: 560, turnRate: 1.7, armLength: 1.5 }, sockets: [sock('hand', 'hand', [-0.12, 0.5, -1.4], [-1, 0, 0], { label: 'Hand Mount' })], desc: 'Hydraulic construction arm. Holds drills, claws and mid-weight guns.' }),
  P({ id: 'arm_heavy', name: 'Heavy Weapon Arm', category: 'arm', classes: M, rarity: 'rare', family: 'heavyjoints', tech: 'heavyjoints', mass: 270, hp: 330, armor: 16, value: 3600, mesh: 'arm', look: { style: 'heavy' }, stats: { loadRating: 1000, turnRate: 1.5, armLength: 1.7 }, sockets: [sock('hand', 'hand', [-0.15, 0.6, -1.55], [-1, 0, 0], { label: 'Hand Mount' })], desc: 'Braced arm for cannons and heavy launchers.' }),
  P({ id: 'mel_claw', name: 'Hydraulic Claw', category: 'melee', classes: M, rarity: 'common', mass: 90, hp: 170, armor: 10, value: 200, mesh: 'melee', look: { style: 'claw' }, stats: { melee: 'claw', damage: 95, pen: 25, reach: 3.2, swingTime: 1.0, powerDraw: 10 }, desc: 'Crushes and tears. Rips armour plates clean off.' }),
  P({ id: 'mel_drill', name: 'Mining Drill', category: 'melee', classes: M, rarity: 'uncommon', mass: 150, hp: 230, armor: 14, value: 1500, mesh: 'melee', look: { style: 'drill' }, stats: { melee: 'drill', damage: 75, pen: 30, reach: 3.1, powerDraw: 40 }, desc: 'Continuous grinding damage to whatever it touches.' }),
  P({ id: 'mel_fist', name: 'Pile-Driver Fist', category: 'melee', classes: M, rarity: 'rare', family: 'heavyjoints', tech: 'heavyjoints', mass: 220, hp: 310, armor: 20, value: 5200, mesh: 'melee', look: { style: 'fist' }, stats: { melee: 'fist', damage: 270, pen: 45, reach: 3.2, swingTime: 1.4, powerDraw: 30, recoil: 9000 }, desc: 'Piston-driven punch that knocks light machines flying.' }),
  P({ id: 'mel_blade', name: 'Chain Blade', category: 'melee', classes: M, rarity: 'epic', mass: 160, hp: 210, armor: 12, value: 12000, mesh: 'melee', look: { style: 'blade' }, stats: { melee: 'blade', damage: 190, pen: 35, reach: 3.6, swingTime: 0.7, powerDraw: 35 }, desc: 'Motorised sword. Fast, vicious, surgical.' }),
  P({ id: 'mel_bucket', name: 'Excavator Bucket Wheel', category: 'melee', classes: M, rarity: 'legendary', mass: 420, hp: 520, armor: 24, value: 36000, unique: true, mesh: 'melee', look: { style: 'bucket' }, stats: { melee: 'drill', damage: 230, pen: 60, reach: 4.2, powerDraw: 150 }, desc: 'The Excavator\'s spinning bucket wheel, rebuilt for a mech arm. Grinds machines into gravel.' }),
  P({ id: 'jj_scrap', name: 'Scrap Jump Jet', category: 'jumpjet', classes: M, rarity: 'uncommon', family: 'rocketry', mass: 60, hp: 70, armor: 4, value: 1300, mesh: 'jumpjet', look: { style: 'scrap' }, tiltable: true, stats: { thrust: 15000, fuelUse: 3, heat: 10, boostTime: 1.8 }, desc: 'Strapped-on rocket for hopping walls and canyon ledges.' }),
  P({ id: 'jj_mil', name: 'Military Jump Pack', category: 'jumpjet', classes: M, rarity: 'rare', family: 'rocketry', mass: 90, hp: 100, armor: 6, value: 5000, mesh: 'jumpjet', look: { style: 'mil' }, tiltable: true, faction: 'authority', stats: { thrust: 28000, fuelUse: 4, heat: 12, boostTime: 2.6 }, desc: 'Twin-nozzle pack that lets heavy mechs leap.' }),
  P({ id: 'hyd_pump', name: 'Hydraulic Pump', category: 'hydraulics', classes: M, rarity: 'uncommon', family: 'hydraulics2', tech: 'hydraulics2', mass: 70, hp: 95, armor: 5, value: 1200, mesh: 'hydraulics', look: { style: 'pump' }, stats: { hydraulicBoost: 1.25, powerDraw: 30 }, desc: 'Boosts every joint on the machine by 25%.' }),
  P({ id: 'hyd_mil', name: 'Military Hydraulics', category: 'hydraulics', classes: M, rarity: 'rare', family: 'heavyjoints', mass: 95, hp: 130, armor: 7, value: 4000, mesh: 'hydraulics', look: { style: 'mil' }, stats: { hydraulicBoost: 1.5, powerDraw: 60 }, desc: 'High-pressure system: +50% joint strength.' }),
];

export const PARTS: PartDef[] = [
  ...FRAMES,
  ...COCKPITS,
  ...ENGINES,
  ...GENERATORS,
  ...BATTERIES,
  ...FUEL,
  ...COOLING,
  ...TRANSMISSIONS,
  ...SUSPENSION,
  ...WHEELS,
  ...TRACKS,
  ...GROUND_MISC,
  ...ARMOR,
  ...WEAPONS,
  ...AIR,
  ...MECH,
];

export const PART_MAP = new Map<string, PartDef>(PARTS.map((p) => [p.id, p]));

export function getPart(id: string): PartDef {
  const p = PART_MAP.get(id);
  if (!p) throw new Error(`Unknown part ${id}`);
  return p;
}

export function registerParts(defs: PartDef[]) {
  for (const d of defs) {
    PARTS.push(d);
    PART_MAP.set(d.id, d);
  }
}

export function partsOfRarity(r: Rarity) {
  return PARTS.filter((p) => p.rarity === r);
}
