// Full app flow: title -> new game -> world -> map/journal/merchant -> garage -> deploy
const app = window.__app;
const out = {};
const step = (s) => { for (let i = 0; i < Math.round(s * 60); i++) game.frame(1 / 60); };
step(0.05);
out.mode0 = app.mode;
await shot('title');
localStorage.clear();
app.beginGame((await import('/src/gameplay/profile.ts')).newProfile(), true);
step(0.03);
await shot('intro');
document.querySelector('.overlay .btn.primary')?.click();
step(0.05);
out.mode1 = app.mode;
out.player = !!game.player;
out.missions = app.missions.active.map((m) => m.title);
out.board = app.missions.board.map((b) => b.title);
game.simulate(2, false);
step(0.05);
await shot('world');
app.map.show();
step(0.02);
await new Promise((r) => setTimeout(r, 200));
out.mapOpen = app.map.open;
await shot('map');
app.map.close();
app.journal.show('board');
step(0.02);
await shot('journal_board');
app.journal.close();
app.journal.show();
step(0.02);
await shot('journal_active');
app.journal.close();
app.merchant.show('rustwater');
step(0.02);
await shot('merchant');
out.visitedMarket = app.profile.flags.visitedMarket;
app.merchant.close();
app.enterGarage(true);
step(0.02);
out.mode2 = app.mode;
await shot('garage');
app.enterWorld(app.profile.activeMachine);
step(0.05);
out.mode3 = app.mode;
return out;
