const app = window.__app;
const P = await import('/src/gameplay/profile.ts');
const log = [];
localStorage.clear();
app.beginGame(P.newProfile(), false);
game.frame(1 / 60);
const st = (label) => log.push(`${label}: active=[${app.missions.active.map((m) => `${m.id}${m.finished ? '(fin)' : ''}:${m.objectives.map((o) => (o.done ? 1 : 0)).join('')}`).join(' ')}] done=[${app.profile.missions.done}] salv=${app.profile.stats.partsSalvaged}`);
st('start');
game.simulate(0.5);
const tut = app.missions.active.find((m) => m.id === 'm_range');
st('after 0.5s');
const pl = game.player;
for (const t of tut.targets) t.damagePartDirect(t.parts.find((p) => p.def.category === 'cockpit'), 1e5, pl, 'test');
game.simulate(0.5);
st('after kills');
log.push(`tut kills=${tut.data.kills} salvagedStart=${tut.data.salvagedStart} same=${app.missions.active.includes(tut)}`);
const w = tut.targets[0];
const T = pl.currPos.constructor;
pl.teleport(new T(w.currPos.x - 8, game.terrain.heightAt(w.currPos.x - 8, w.currPos.z) + 1.5, w.currPos.z), Math.PI / 2);
game.simulate(1);
st('after teleport');
const c = app.salvage.candidates(w).sort((a, b) => a.def.mass - b.def.mass)[0];
app.salvage.start(w, [c], false);
for (let i = 0; i < 30 && app.salvage.job; i++) game.simulate(0.5);
st('after salvage');
game.simulate(0.5);
st('after +0.5');
app.enterGarage(true);
st('in garage');
log.push(`tut finished=${tut.finished} failed=${tut.failed} inActive=${app.missions.active.includes(tut)}`);
return log;
